package bibliotecagrupo5.Vistas;

import bibliotecagrupo5.AccesoADatos.PrestamoData;
import bibliotecagrupo5.Entidades.Prestamo;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.TreeSet;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author BETO
 */
public class ConsultaEjemplaresPrestadosPorFecha extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };

    private PrestamoData prestamoData = new PrestamoData();

    /**
     * Creates new form ConsultaPrestamoPorFecha
     */
    public ConsultaEjemplaresPrestadosPorFecha() {
        initComponents();
        armarCabecera();
        ajustarTamañoColumnas();

        jdchFechaInicio1.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if ("date".equals(evt.getPropertyName())) {
                    cargarPrestamosPorFechas();
                }
            }
        });

        jdchFechaInicio2.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if ("date".equals(evt.getPropertyName())) {
                    cargarPrestamosPorFechas();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdchFechaInicio1 = new com.toedter.calendar.JDateChooser();
        jdchFechaInicio2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPrestamo = new javax.swing.JTable();
        jLabelEntre = new javax.swing.JLabel();
        jbNuevo = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Consulta Prestamo por Fecha");

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setText("Ejemplares Prestados");

        jLabel2.setText("Fecha de Inicio:");

        jTPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTPrestamo.getTableHeader().setResizingAllowed(false);
        jTPrestamo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTPrestamo);

        jLabelEntre.setText("entre");

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdchFechaInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabelEntre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jdchFechaInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jbNuevo)
                        .addGap(213, 213, 213)
                        .addComponent(jbSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel1)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdchFechaInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jdchFechaInicio2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEntre))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jbSalir))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        borrarCampos();
        borrarTabla();
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea Salir?",
                "Salir", JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        if (respuesta == 0) {
            dispose();
        }
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEntre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTPrestamo;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private com.toedter.calendar.JDateChooser jdchFechaInicio1;
    private com.toedter.calendar.JDateChooser jdchFechaInicio2;
    // End of variables declaration//GEN-END:variables
     private void armarCabecera() {
        modelo.addColumn("ID Prestamo");
        modelo.addColumn("Fecha Prestamo");
        modelo.addColumn("Titulo");
        modelo.addColumn("Autor");
        modelo.addColumn("Categoria");
        jTPrestamo.setModel(modelo);
    }

    private void ajustarTamañoColumnas() {
        TableColumn columnaIdPrestamo = jTPrestamo.getColumnModel().getColumn(0);
        columnaIdPrestamo.setPreferredWidth(80);

        TableColumn columnaFechaPrestamo = jTPrestamo.getColumnModel().getColumn(1);
        columnaFechaPrestamo.setPreferredWidth(80);

        TableColumn columnaTitulo = jTPrestamo.getColumnModel().getColumn(2);
        columnaTitulo.setPreferredWidth(100);

        TableColumn columnaAutor = jTPrestamo.getColumnModel().getColumn(3);
        columnaAutor.setPreferredWidth(100);

        TableColumn columnaCategoria = jTPrestamo.getColumnModel().getColumn(4);
        columnaCategoria.setPreferredWidth(100);

    }

    private void cargarTablaLista(TreeSet<Prestamo> listaPrestamos) {
        for (Prestamo prestamo : listaPrestamos) {
            modelo.addRow(new Object[]{
                prestamo.getIdPrestamo(),
                prestamo.getFechaInicio(),
                prestamo.getEjemplar().getLibro().getTitulo(),
                prestamo.getEjemplar().getLibro().getAutor(),
                prestamo.getEjemplar().getLibro().getTipo(),});
        }
    }

    private void cargarPrestamosPorFechas() {

        try {
            LocalDate fechaInicio1 = jdchFechaInicio1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaInicio2 = jdchFechaInicio2.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            if (fechaInicio1.isBefore(fechaInicio2)) {
                borrarTabla();
                TreeSet<Prestamo> listaprestamos = prestamoData.obtenerPrestamosPorRangoDeFechas(fechaInicio1, fechaInicio2);
                cargarTablaLista(listaprestamos);
            }else{
                JOptionPane.showMessageDialog(this, "La segunda fecha debe ser igual o mayor a la primera");
                jdchFechaInicio2.setDate(null);
             }
        } catch (NullPointerException e) {
            
        }

    }

    private void borrarTabla() {
        modelo.setRowCount(0);
    }

    private void borrarCampos() {
        jdchFechaInicio1.setDate(null);
        jdchFechaInicio2.setDate(null);

    }

}
