package bibliotecagrupo5.Vistas;

import bibliotecagrupo5.AccesoADatos.EjemplarData;
import bibliotecagrupo5.AccesoADatos.LibroData;
import bibliotecagrupo5.Entidades.Condicion;
import bibliotecagrupo5.Entidades.Ejemplar;
import bibliotecagrupo5.Entidades.Libro;
import javax.swing.JSpinner;
import bibliotecagrupo5.Entidades.Tipo;
import java.util.TreeSet;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author BETO
 */
public class GestionDeLibros extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            if (c == 0 || c == 1) {
                return false;
            }
            return true;
        }
    };

    private LibroData libroData = new LibroData();
    private EjemplarData ejemplarData = new EjemplarData();
    private Libro libro = null;

    /**
     * Creates new form GestionDeLibros
     */
    public GestionDeLibros() {
        initComponents();

        JSpinner spinner = (JSpinner) jycAnio.getSpinner();
        ((javax.swing.JTextField) spinner.getEditor()).setEditable(false);

        cargarCombo();
        armarCabecera();
        ajustarTamañoColumnas();

        crearComboBoxParaColumna();

        borrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();
        jtfISBN = new javax.swing.JTextField();
        jtfTitulo = new javax.swing.JTextField();
        jtfAutor = new javax.swing.JTextField();
        jtfEditorial = new javax.swing.JTextField();
        jycAnio = new com.toedter.calendar.JYearChooser();
        jbNuevo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfPorISBN = new javax.swing.JTextField();
        jtfPorTitulo = new javax.swing.JTextField();
        jbBuscarISBN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTLibros = new javax.swing.JTable();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbClear = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestion de Libros");

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Formulario Libros");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("ISBN:");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setText("Titulo:");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setText("Autor:");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setText("Año:");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel6.setText("Tipo:");

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel7.setText("Editorial:");

        jbNuevo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotecagrupo5/ImagenesVideosGif/nuevo.png"))); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbGuardar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotecagrupo5/ImagenesVideosGif/guardar.png"))); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotecagrupo5/ImagenesVideosGif/Image20231018165055 (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbNuevo)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTitulo)
                            .addComponent(jtfISBN)
                            .addComponent(jtfAutor)
                            .addComponent(jycAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbTipo, 0, 191, Short.MAX_VALUE)
                            .addComponent(jtfEditorial))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbGuardar)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jycAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jbGuardar))
                .addGap(88, 88, 88))
        );

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Modificacion");

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel9.setText("Ingrese ISBN:");

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel10.setText("Ingrese primeras letras Titulo:");

        jtfPorTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPorTituloKeyReleased(evt);
            }
        });

        jbBuscarISBN.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jbBuscarISBN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotecagrupo5/ImagenesVideosGif/buscar.png"))); // NOI18N
        jbBuscarISBN.setText("Buscar ISBN");
        jbBuscarISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarISBNActionPerformed(evt);
            }
        });

        jTLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTLibros.getTableHeader().setResizingAllowed(false);
        jTLibros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTLibros);
        if (jTLibros.getColumnModel().getColumnCount() > 0) {
            jTLibros.getColumnModel().getColumn(0).setResizable(false);
            jTLibros.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTLibros.getColumnModel().getColumn(1).setResizable(false);
            jTLibros.getColumnModel().getColumn(2).setResizable(false);
            jTLibros.getColumnModel().getColumn(3).setResizable(false);
            jTLibros.getColumnModel().getColumn(4).setResizable(false);
            jTLibros.getColumnModel().getColumn(5).setResizable(false);
            jTLibros.getColumnModel().getColumn(6).setResizable(false);
        }

        jbModificar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jbModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotecagrupo5/ImagenesVideosGif/escribir.png"))); // NOI18N
        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotecagrupo5/ImagenesVideosGif/eliminar.png"))); // NOI18N
        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbClear.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jbClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotecagrupo5/ImagenesVideosGif/limpiar.png"))); // NOI18N
        jbClear.setText("Limpiar");
        jbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClearActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotecagrupo5/ImagenesVideosGif/salir.png"))); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(287, 287, 287)
                                .addComponent(jLabel8))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jtfPorISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(jbBuscarISBN))
                                    .addComponent(jtfPorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jbModificar)
                        .addGap(65, 65, 65)
                        .addComponent(jbEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbClear)
                        .addGap(64, 64, 64)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jtfPorISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscarISBN)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfPorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModificar)
                    .addComponent(jbEliminar)
                    .addComponent(jbClear)
                    .addComponent(jbSalir))
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        try {
            if (!comprobarCamposVacios()) {
                long isbn = Long.parseLong(jtfISBN.getText());
                if (isbn > 0) {
                    String titulo = jtfTitulo.getText();
                    String autor = jtfAutor.getText();
                    int anio = jycAnio.getYear();
                    Tipo tipo = (Tipo) jcbTipo.getSelectedItem();
                    String editorial = jtfEditorial.getText();

                    if (libroData.buscarLibroPorIsbn(isbn) == null) {
                        libro = new Libro(isbn, titulo, autor, anio, tipo, editorial, true);
                        libroData.guardarLibro(libro);
                        JOptionPane.showMessageDialog(this, "Libro Guardado");
                    } else {
                        JOptionPane.showMessageDialog(this, "Ya existe un libro con ese N° de ISBN");
                    }
                    borrarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "El número correspondiente al ISBN debe ser positivo");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Los campos de datos de libro no deben estar vacíos");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número entero positivo en el ISBN");
            jtfISBN.setText("");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        borrarCampos();
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbBuscarISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarISBNActionPerformed
        // TODO add your handling code here:
        borrarTabla();
        jtfPorTitulo.setText("");
        try {
            if (!jtfPorISBN.getText().isEmpty()) {

                long isbn = Long.parseLong(jtfPorISBN.getText());

                if (isbn > 1) {
                    Libro libro2 = libroData.buscarLibroPorIsbn(isbn);

                    if (libro2 != null) {
                        cargarTabla(libro2);
                    } else {
                        jtfPorISBN.setText("");
                        JOptionPane.showMessageDialog(this, "No se encontró el libro con el isbn " + isbn);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Debe ingresar un número entero positivo en el ISBN ");
                }
            } else {
                JOptionPane.showMessageDialog(this, "El campo ISBN no debe estar vacio");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número entero positivo en el ISBN ");
            jtfPorISBN.setText("");
        }

    }//GEN-LAST:event_jbBuscarISBNActionPerformed

    private void jtfPorTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPorTituloKeyReleased
        // TODO add your handling code here:
        jtfPorISBN.setText("");

        TreeSet<Libro> listaLibros = libroData.listarLibros();
        cargarTablaPorTitulo(listaLibros);

    }//GEN-LAST:event_jtfPorTituloKeyReleased

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTLibros.getSelectedRow();

        try {
            if (filaSeleccionada != -1) {

                int idLibro = (Integer) jTLibros.getValueAt(filaSeleccionada, 0);
                long isbn = (Long) jTLibros.getValueAt(filaSeleccionada, 1);
                String titulo = jTLibros.getValueAt(filaSeleccionada, 2).toString();
                String autor = jTLibros.getValueAt(filaSeleccionada, 3).toString();
                int anio = Integer.parseInt(jTLibros.getValueAt(filaSeleccionada, 4).toString());
                Tipo tipo = Tipo.valueOf(jTLibros.getValueAt(filaSeleccionada, 5).toString());
                String editorial = jTLibros.getValueAt(filaSeleccionada, 6).toString();

                if (anio > 0 && anio <= 9999) {

                    if (!comprobarFilasVacias(filaSeleccionada)) {

                        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea modificar el libro?",
                                "Modificacion", JOptionPane.YES_NO_OPTION,
                                JOptionPane.INFORMATION_MESSAGE);

                        if (respuesta == 0) {
                            libro = libroData.buscarLibro(idLibro);

                            libro.setTitulo(titulo);
                            libro.setAutor(autor);
                            libro.setAnio(anio);
                            libro.setTipo(tipo);
                            libro.setEditorial(editorial);

                            libroData.modificarLibro(libro);
                            JOptionPane.showMessageDialog(this, "Libro Modificado");
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "Algunos campos estan vacios, debe ingresar datos en ellos");
                    }
                    jTLibros.clearSelection();
                } else {
                    JOptionPane.showMessageDialog(this, "Debe ingresar un año válido ");

                }

            } else {
                JOptionPane.showMessageDialog(this, "Debe selecionar una fila");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un año válido: " + ex.getMessage());
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTLibros.getSelectedRow();

        try {
            if (filaSeleccionada != -1) {
                int idLibro = (Integer) jTLibros.getValueAt(filaSeleccionada, 0);

                TreeSet<Ejemplar> listaEjemplares = ejemplarData.listarEjemplaresNoDisponibles(idLibro, Condicion.DISPONIBLE);

                //SI NO ENCUENTRA LIBROS NO DISPONIBLES (PRESTADOS, REPARACION, RETRASO) RECIEN PERMITE ELIMINAR
                if (listaEjemplares.isEmpty()) {
                    int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el libro con id " + idLibro + " ?",
                            "Eliminacion", JOptionPane.YES_NO_OPTION,
                            JOptionPane.INFORMATION_MESSAGE);

                    if (respuesta == 0) {
                        libroData.eliminarLibro(idLibro);
                        JOptionPane.showMessageDialog(this, "Libro Eliminado");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "No puede eliminar el libro con id " + idLibro + " "
                            + "- Existen ejemplares con la condicion Prestado, Retraso o Reparacion");
                }

                jTLibros.clearSelection();

            } else {
                JOptionPane.showMessageDialog(this, "Debe selecionar una fila");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un año válido: " + ex.getMessage());
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearActionPerformed
        // TODO add your handling code here:
        jtfPorISBN.setText("");
        jtfPorTitulo.setText("");
        borrarTabla();
    }//GEN-LAST:event_jbClearActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea Salir?",
                "Salir", JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        if (respuesta == 0) {
            dispose();
        }
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTLibros;
    private javax.swing.JButton jbBuscarISBN;
    private javax.swing.JButton jbClear;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Tipo> jcbTipo;
    private javax.swing.JTextField jtfAutor;
    private javax.swing.JTextField jtfEditorial;
    private javax.swing.JTextField jtfISBN;
    private javax.swing.JTextField jtfPorISBN;
    private javax.swing.JTextField jtfPorTitulo;
    private javax.swing.JTextField jtfTitulo;
    private com.toedter.calendar.JYearChooser jycAnio;
    // End of variables declaration//GEN-END:variables
    private void cargarCombo() {
        jcbTipo.setModel(new DefaultComboBoxModel<>(Tipo.values()));
    }

    private void armarCabecera() {
        modelo.addColumn("ID");
        modelo.addColumn("ISBN");
        modelo.addColumn(("Titulo"));
        modelo.addColumn("Autor");
        modelo.addColumn("Año");
        modelo.addColumn("Tipo");
        modelo.addColumn("Editorial");
        jTLibros.setModel(modelo);
    }

    private void ajustarTamañoColumnas() {
        TableColumn columnaIdLibro = jTLibros.getColumnModel().getColumn(0);
        columnaIdLibro.setPreferredWidth(5);

        TableColumn columnaIsbn = jTLibros.getColumnModel().getColumn(1);
        columnaIsbn.setPreferredWidth(70);

        TableColumn columnaTitulo = jTLibros.getColumnModel().getColumn(2);
        columnaTitulo.setPreferredWidth(150);

        TableColumn columnaAutor = jTLibros.getColumnModel().getColumn(3);
        columnaAutor.setPreferredWidth(100);

        TableColumn columnaAño = jTLibros.getColumnModel().getColumn(4);
        columnaAño.setPreferredWidth(20);

        TableColumn columnaTipo = jTLibros.getColumnModel().getColumn(5);
        columnaTipo.setPreferredWidth(50);

        TableColumn columnaEditorial = jTLibros.getColumnModel().getColumn(6);
        columnaEditorial.setPreferredWidth(70);
    }

    private void borrarCampos() {
        jtfISBN.setText("");
        jtfTitulo.setText("");
        jtfAutor.setText("");
        jycAnio.setYear(2023);
        jcbTipo.setSelectedIndex(0);
        jtfEditorial.setText("");
    }

    private boolean comprobarCamposVacios() {
        return jtfISBN.getText().isEmpty() && jtfTitulo.getText().isEmpty()
                && jtfAutor.getText().isEmpty() && jtfEditorial.getText().isEmpty();
    }

    private void cargarTabla(Libro libro) {
        modelo.addRow(new Object[]{libro.getIdLibro(), libro.getIsbn(), libro.getTitulo(),
            libro.getAutor(), libro.getAnio(), libro.getTipo(), libro.getEditorial()});
    }

    private void borrarTabla() {
        modelo.setRowCount(0);
    }

    private void borrarFilas() {
        int filas = jTLibros.getRowCount() - 1;
        for (int f = filas; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }

    private void cargarTablaPorTitulo(TreeSet<Libro> listaLibros) {
        borrarFilas();
        for (Libro libro : listaLibros) {

            if (libro.getTitulo().toLowerCase().startsWith(jtfPorTitulo.getText().toLowerCase()) && !jtfPorTitulo.getText().isEmpty()) {
                cargarTabla(libro);
            }

        }
    }

    private void crearComboBoxParaColumna() {
        JComboBox<Tipo> comboBox = new JComboBox<>(Tipo.values());
        DefaultCellEditor customEditor = new DefaultCellEditor(comboBox);

        jTLibros.getColumnModel().getColumn(5).setCellEditor(customEditor);
    }

    private boolean comprobarFilasVacias(int filaSeleccionada) {
        String titulo = jTLibros.getValueAt(filaSeleccionada, 2).toString();
        String autor = jTLibros.getValueAt(filaSeleccionada, 3).toString();
        String editorial = jTLibros.getValueAt(filaSeleccionada, 6).toString();

        return titulo.equals("") || autor.equals("") || editorial.equals("");
    }

}
